import type { Metadata } from 'next';
import { unstable_setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider, useMessages } from 'next-intl';

import NextTopLoader from 'nextjs-toploader';
import { Toaster } from 'sonner';

import LoginWindowContextProvider from '@/contexts/LoginWindowContext';
import LoadingContextProvider from '@/contexts/LoadingContext';
import DeleteContextProvider from '@/contexts/DeleteContext';

import AnimatedBg from '@/components/AnimatedBg';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import DeleteDialog from '@/components/DeleteDialog';
import LoginWindow from '@/components/login/LoginWindow';

import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        // locale: string;
        // middlewareból jön
        locale: 'hu' | 'en' | 'de';
    };
}

export default function RootLayout({ children, params: { locale } }: Readonly<RootLayoutProps>) {
    const messages = useMessages();
    unstable_setRequestLocale(locale);

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    <LoadingContextProvider>
                        <ThemeProvider>
                            <LoginWindowContextProvider>
                                <DeleteContextProvider>
                                    <Header />
                                    <LoginWindow />
                                    <NextTopLoader color={'var(--primary)'} showSpinner={false} />
                                    <main className='main-content'>{children}</main>
                                    <DeleteDialog />
                                    <Footer />
                                    <Toaster position='bottom-left' className='toaster' />
                                </DeleteContextProvider>
                            </LoginWindowContextProvider>
                        </ThemeProvider>
                    </LoadingContextProvider>
                </NextIntlClientProvider>
                <AnimatedBg />
            </body>
        </html>
    );
}
