import type { Metadata } from 'next';
import AnimatedBg from '@/components/AnimatedBg';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Toaster } from 'sonner';
import LoginWindowContextProvider from '@/contexts/LoginWindowContext';
import LoginWindow from '@/components/login/LoginWindow';
import { createSerClient } from '@/lib/supabase/server';
import { unstable_setRequestLocale } from 'next-intl/server';
import LoadingContextProvider from '@/contexts/LoadingContext';
import NextTopLoader from 'nextjs-toploader';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        // locale: string;
        // middlewareból jön
        locale: 'hu' | 'en' | 'de';
    };
}

export default function RootLayout({ children, params: { locale } }: Readonly<RootLayoutProps>) {
    const messages = useMessages();
    unstable_setRequestLocale(locale);
    // const t = useTranslations('Hero');
    // const supabase = await createSerClient();
    // const user = await supabase.auth.getUser();
    // console.log('user', user);

    return (
        <html lang='en'>
            <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    <LoadingContextProvider>
                        <LoginWindowContextProvider>
                            <Header />
                            <LoginWindow />
                        </LoginWindowContextProvider>
                        <NextTopLoader color={'var(--primary)'} />
                        <main className='main-content'>{children}</main>
                        <Footer />
                        <Toaster position='bottom-left' className='toaster' />
                    </LoadingContextProvider>
                </NextIntlClientProvider>
                <AnimatedBg />
            </body>
        </html>
    );
}
